# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-01 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('js_vacancies', '0002_remove_vacancy_related'),
    ]

    #operations = [
        #migrations.AlterField(
            #model_name='vacancy',
            #name='location',
            #field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='js_locations.Location', verbose_name='location'),
        #),
    #]
