# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-02 05:20
from __future__ import unicode_literals

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('js_companies', '0001_initial'),
        ('js_vacancies', '0003_auto_20190401_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='companies',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='js_companies.Company', verbose_name='companies'),
        ),
    ]
